---
title: "HW5"
author: "Madelyn Maclaughlin"
date: "2024-11-04"
output: pdf_document
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```

Load in the data:
```{r}
library(tidyverse)
homicides <- read.csv('/Users/madelynmaclaughlin/Downloads/R_class/Ch_9/data/homicides.csv')
head(homicides)
```

I am creating the graph from choice 2. Let's try and reduce the data to what we need and organize it.
```{r}
homicides_dates <- homicides %>% 
  select(reported_date, city) %>% 
  filter(city == "Baltimore") %>% 
  mutate(reported_date = ymd(reported_date)) %>% 
  arrange(reported_date)
head(homicides_dates)
```

Sorting data into different groups based on season.
```{r}
summer <- homicides_dates %>% 
  mutate(months = month(reported_date, label = FALSE),
         years = year(reported_date)) %>% 
  filter(months %in% c(5, 6, 7, 8, 9, 10)) %>% 
  group_by(months, years) %>% 
  count() %>% 
  mutate(total_date = paste(years, months, sep = "-")) %>% 
  mutate(total_date = ym(total_date))
  
winter <- homicides_dates %>% 
  mutate(months = month(reported_date, label = FALSE),
         years = year(reported_date)) %>% 
  filter(months %in% c(11, 12, 1, 2, 3, 4)) %>% 
  group_by(months, years) %>% 
  count() %>% 
  mutate(total_date = paste(years, months, sep = "-")) %>% 
  mutate(total_date = ym(total_date))
```

Create a dataset of frequency for the geom_smooth function
```{r}
h_freq <- homicides_dates %>% 
  mutate(month = round_date(reported_date, unit = "month")) %>% 
  group_by(month) %>% 
  count()
```


Begin graphing.
```{r, fig.width = 7, fig.height = 2.2}
ggplot() +
  geom_col(summer, mapping = aes(x = total_date, y = n), fill = "lightgray", color = "gray50") +
  geom_col(winter, mapping = aes(x = total_date, y = n), fill = "lightblue", color = "gray50") +
  geom_smooth(h_freq, mapping =  aes(x = month, y = n), se = FALSE, span = 0.1) +
  theme_dark() +
  labs(x = "Date", y = "Monthly Homicides", title = "Homicides in Baltimore, MD") +
  scale_y_continuous(breaks = c(0, 10, 20, 30, 40)) +
  geom_vline(xintercept = ymd("2015-04-12"), linewidth = 1.5, linetype = 8, color = "red") +
  geom_text(aes(x = ymd("2015-01-01"), y = 37, label = "Arrest of\nFreddie Gray"), color = "white", hjust = 1) 
```












